name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  AppCD:
    runs-on: ubuntu-20.04
    steps:
      - name: Generate IaC
        uses: appcd-dev/action@v0
        env:
          APPCD_TOKEN: ${{ secrets.APPCD_TOKEN }}
        with:
          cloud: 'aws' # Specify the cloud provider
          language: 'Python' # Set the programming language
          outputDir: './iac' # Define the output directory
          scanPath: '.' # Indicate the path to scan
          targetCompute: 'k8s' # Choose the target compute platform
          cleanup: 'true' # Cleanup after action

      
